Fix "Plugin 'pytest_cov' could not be loaded"
pytest has to be upgraded in order to pass the Travis-CI build

Otherwise the following error message is raised:
pluggy.manager.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 4.3.1 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('pytest>=4.6'))!